title:              Bikky Kumar
email:              vikspython@gmail.com
form_name:          mdoyoblo
description:        A Blog Theme by Start Bootstrap
author:             Bikky
baseurl:            ""
url:                "https://bkumar86.github.io"

# Social Profiles
twitter_username:
github_username: bkumar86
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge
